// <auto-generated />
using System;
using BetaLottery.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BetaLottery.Migrations
{
    [DbContext(typeof(MyContext))]
    [Migration("20220927140314_BetaLottery")]
    partial class BetaLottery
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("BetaLottery.Models.Client", b =>
                {
                    b.Property<int>("ClientId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("ClientId");

                    b.ToTable("Clients");
                });

            modelBuilder.Entity("BetaLottery.Models.Participate", b =>
                {
                    b.Property<int>("ParticipateId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("ClientId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("ParticipateId");

                    b.HasIndex("ClientId");

                    b.HasIndex("ProductId");

                    b.ToTable("Participates");
                });

            modelBuilder.Entity("BetaLottery.Models.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("NameOfProduct")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("PromoterUserId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("ProductId");

                    b.HasIndex("PromoterUserId");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("BetaLottery.Models.PromoterUser", b =>
                {
                    b.Property<int>("PromoterUserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("PromoterUserId");

                    b.ToTable("PromoterUsers");
                });

            modelBuilder.Entity("BetaLottery.Models.Participate", b =>
                {
                    b.HasOne("BetaLottery.Models.Client", "MyClient")
                        .WithMany("Participates")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BetaLottery.Models.Product", "MyProduct")
                        .WithMany("Participates")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MyClient");

                    b.Navigation("MyProduct");
                });

            modelBuilder.Entity("BetaLottery.Models.Product", b =>
                {
                    b.HasOne("BetaLottery.Models.PromoterUser", "MyPromotion")
                        .WithMany("CreatedProducts")
                        .HasForeignKey("PromoterUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MyPromotion");
                });

            modelBuilder.Entity("BetaLottery.Models.Client", b =>
                {
                    b.Navigation("Participates");
                });

            modelBuilder.Entity("BetaLottery.Models.Product", b =>
                {
                    b.Navigation("Participates");
                });

            modelBuilder.Entity("BetaLottery.Models.PromoterUser", b =>
                {
                    b.Navigation("CreatedProducts");
                });
#pragma warning restore 612, 618
        }
    }
}
